### ISSUE TITLE
Hi, any plan to support multiple chats?

### ISSUE THREAD

**Issue by ruleroller** [simonlaw101/tg_bot#3]
This is me again~ :)

How to make the bot work in a Group? 

I didn't find where to set Chat IDs, so I guess now the bot only works for one to one private chat, right?

Thanks for your hard work on #1 .

**Comment by simonlaw101** [comment]
Hello @ruleroller, nice to see you again :)
I just tested in Private Group and it works fine.

May I know which function/command are you testing?

Would it be permission problem in the group setting? Both "Send Messages" and "Send Media" options should be allowed.

And I think clicking the command menu bar directly might be the cause too. It will add a tag of the bot name after the command, e.g. /s@YourBot, making it not working.

You can try clicking the little arrow on the right hand side of the command menu first (this will not add a bot name tag). At the same time, let me add a line of code to replace the name tag with empty string.

**Comment by ruleroller** [comment]
Haha, long time no see, @simonlaw101 .

It's wierd that I create another group and only me with the bot, 2 members in the group, all commands works. /start /h /s /c etc, 

Then, I add a third member, another bot, all commands stop working.. And after I remove the third member, commands work again!!

I also tried /h@botname , they never work.

**Comment by simonlaw101** [comment]
Oh, I just realized that there is a Privacy Mode setting. 😮

"By default, all bots added to groups run in Privacy Mode and only see relevant messages and commands"

[https://core.telegram.org/bots/features#privacy-mode](https://core.telegram.org/bots/features#privacy-mode) 

Maybe can try to disable it or set it to admin first (need to re-add the bot to the group to take effect). 

Let me study and handle this multiple bots situation. 👍🏻

**Comment by simonlaw101** [comment]
@ruleroller  Thanks for testing the bot :)
I would like to invite you as collaborator.
It will be great if you can join and make fun together!

We can chat on telegram as well~
can let me know your telegram username thru email: cc538604@gmail.com

**Comment by ruleroller** [comment]
I don't know much about github and code. So I don't know what "collaborator" is.  I feel that this is a responsibility I'm afraid I cannot bear. For now, I will have to decline this invitation. Nevertheless, I appreciate your kind offer. But I will continue to submit bug reports here.

😏
