### ISSUE TITLE
 Unable to get the prices of most stocks, show's "NA" instead

### ISSUE THREAD

**Issue by ruleroller** [simonlaw101/tg_bot#6]
And when I specifically check a certain stock, like "TON11419-USD", it says: 
`Please enter a valid stock code.`

![image](https://github.com/simonlaw101/tg_bot/assets/3047708/5c3d6828-4bb5-4519-b340-d46c956f0fb7)

**Comment by ruleroller** [comment]
This might be a temporary error. Sorry for bothering you.

**Comment by ruleroller** [comment]
This issue has persisted for several months. Could the developer please take a look and see what might be causing it? Is it possible to fix it?

**Comment by simonlaw101** [comment]
Hi @ruleroller, I found the root cause:
1. browser's user agent is invalid
2. The class name of the html element has been changed in web scraping

Fixed and please retry. 

![retest](https://github.com/simonlaw101/tg_bot/assets/44299484/fc877b3c-5a4e-4ab4-9bdb-29b35d6b54ae)

**Comment by ruleroller** [comment]
The /s command seems broken?
![image](https://github.com/user-attachments/assets/0ff7a75c-ec18-415e-a6ae-f917051d778f)

**Comment by simonlaw101** [comment]
Hi @ruleroller, issue fixed.

**Comment by ruleroller** [comment]
Hi, again..  /alert and /s  shows "NA". 

Hoping it can be fixed again.

❤️

**Comment by ruleroller** [comment]
@simonlaw101 help~  😢   https://github.com/simonlaw101/tg_bot/issues/6#issuecomment-2451930595
